#!/usr/bin/env bash
# Generate a throwaway credential registry for performance testing.
#
#   bash performance-tests/scripts/setup-env.sh
#
# Writes performance-tests/.env.perf, which is gitignored. The key it contains
# is generated locally, is valid only for the disposable Compose stack, and
# must never be committed or reused anywhere else.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
env_file="$repo_root/performance-tests/.env.perf"

if [ -f "$env_file" ] && [ "${ARR_PERF_FORCE:-0}" != "1" ]; then
  echo "$env_file already exists. Set ARR_PERF_FORCE=1 to regenerate."
  exit 0
fi

python_bin="$repo_root/.venv/bin/python"
if [ ! -x "$python_bin" ]; then
  echo "Run 'uv sync --dev' first: $python_bin not found." >&2
  exit 1
fi

pepper="$(head -c 48 /dev/urandom | base64 | tr -d '/+=' | head -c 40)"
credential_json="$(APP_AUTH_PEPPER="$pepper" "$python_bin" -m agent_runtime.security.cli \
  --principal perf-principal --tenant perf-tenant)"

APP_AUTH_PEPPER="$pepper" CREDENTIAL_JSON="$credential_json" ENV_FILE="$env_file" \
  "$python_bin" - <<'PY'
import json
import os

payload = json.loads(os.environ["CREDENTIAL_JSON"])
lines = [
    "# Generated by performance-tests/scripts/setup-env.sh - DO NOT COMMIT.",
    "# Throwaway credential for the disposable local performance stack only.",
    f"APP_AUTH_PEPPER={os.environ['APP_AUTH_PEPPER']}",
    # Single-quoted: `set -a; . .env.perf` strips unquoted double quotes, which
    # silently turns the registry into invalid JSON.
    "APP_AUTH_CREDENTIALS='"
    + json.dumps([payload["credential"]], separators=(",", ":"))
    + "'",
    f"ARR_API_KEY={payload['api_key']}",
    "GRAFANA_ADMIN_PASSWORD=" + os.urandom(16).hex(),
]
with open(os.environ["ENV_FILE"], "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines) + "\n")
os.chmod(os.environ["ENV_FILE"], 0o600)
print(f"Wrote {os.environ['ENV_FILE']} (key_id {payload['credential']['key_id']})")
PY

echo "Load it with: set -a; . performance-tests/.env.perf; set +a"
